---

  - name: Installing NTP
    apt:
      name:
        - chrony
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Editing Chrony File
    copy:
      dest: /etc/chrony/chrony.conf
      content: |
        server NTP_SERVER iburst
        allow 10.0.0.0/24
      mode: 0755
    when: ansible_distribution == "Ubuntu"

  - name: Enable NTP
    service:
      name: chrony
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: Restarting NTP
    service:
      name: chrony
      state: restarted
    when: ansible_distribution == "Ubuntu"
