---
  - name: Installing ETCD
    apt:
      name:
        - etcd
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Editing ETCD File
    copy:
      dest: /etc/default/etcd
      content: |
        ETCD_NAME="controller"
        ETCD_DATA_DIR="/var/lib/etcd"
        ETCD_INITIAL_CLUSTER_STATE="new"
        ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-01"
        ETCD_INITIAL_CLUSTER="controller=http://127.0.0.1:2380"
        ETCD_INITIAL_ADVERTISE_PEER_URLS="http://127.0.0.1:2380"
        ETCD_ADVERTISE_CLIENT_URLS="http://127.0.0.1:2379"
        ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
        ETCD_LISTEN_CLIENT_URLS="http://127.0.0.1:2379"
      mode: 0755
    when: ansible_distribution == "Ubuntu"

  - name: Shutting Down ETCD
    service:
      name: etcd
      state: stopped
    when: ansible_distribution == "Ubuntu"

  - name: Restarting ETCD
    service:
      name: etcd
      state: started
    when: ansible_distribution == "Ubuntu"

  - name: Enabling ETCD
    service:
      name: etcd
      enabled: yes
    when: ansible_distribution == "Ubuntu"
